credentials:
  usernames:
    jdoe:
      email: jdoe@gmail.com
      name: Jane Doe
      password: $2b$12$xyU4ZxrQpnKUxjoG3bCHEuruBA/VwcuPCOqw8SMM.MqZMGwBdc3nG
      # when logging into the app type in abc for your password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com